#!/bin/sh 
# vim: ft=sh

case "$1" in 
    next)
        killall -HUP muz-core
        ;;
    kill)
        killall muz-core
        ;;
    *)
        ./muz-core > /dev/null 2> /dev/null &
        ;;
esac
