#!/bin/sh
# vim: ft=sh

echo "pid: $$"
stat /tmp/muz-playerpid && PLAYER_PID=$(cat /tmp/muz-playerpid)

MUSIC="$HOME/music"

pause(){
    kill -STOP $PLAYER_PID
}

resume(){
    kill -CONT $PLAYER_PID
}

playnew(){
    ffplay -nodisp "$1"&
    export PLAYER_PID=$!
    echo $PLAYER_PID > /tmp/muz-playerpid
    notify-send "Playing $(basename "$FILE")" 
}

playfifo(){
    playnew $(head -n1 $1) && sed -i 1d $1
}

[[ -s $1 ]] && playfifo $1

case "$1" in 
    pause)
        pause
        ;;
    resume)
        resume
        ;;
    *)
        playnew $(find "$MUSIC" -type f -not -path "$FILE" | shuf -n1)
        ;;
esac
