#!/bin/sh
# vim: ft=sh

echo "pid: $$"
stat /tmp/muz-playerpid && PLAYER_PID=$(cat /tmp/muz-playerpid)
echo $$ > /tmp/muz-pid

MUSIC="$HOME/music"

pause(){
    kill -STOP $PLAYER_PID
}

resume(){
    kill -CONT $PLAYER_PID
}

playnew(){
    FILE=$(find "$MUSIC" -type f -not -path "$FILE" | shuf -n1)
    ffplay -nodisp "$FILE"&
    export PLAYER_PID=$!
    echo $PLAYER_PID > /tmp/muz-playerpid
    notify-send "Playing $(basename "$FILE")" 
}

case "$1" in 
    pause)
        pause
        ;;
    resume)
        resume
        ;;
    *)
        playnew
        ;;
esac
